name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Rust format
        run: cargo fmt -- --check
      - name: Rust tests
        run: cargo test --quiet
      - name: Frontend install
        run: npm ci
        working-directory: frontend
      - name: Frontend tests
        run: npm test --silent
        working-directory: frontend

